services:
  app:
    build: .
    ports:
      - "${APP_PORT:-8080}:80"
    environment:
      - DB_HOST=${DB_HOST:-db}
      - DB_NAME=${DB_NAME:-enrichment_db}
      - DB_USER=${DB_USER:-user}
      - DB_PASS=${DB_PASS:-userpassword}
      - PORT=${PORT:-80}
    depends_on:
      - db
    volumes:
      - .:/var/www/html

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpassword}
      - MYSQL_DATABASE=${DB_NAME:-enrichment_db}
      - MYSQL_USER=${DB_USER:-user}
      - MYSQL_PASSWORD=${DB_PASS:-userpassword}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
